# Generated by Django 3.2.12 on 2022-12-10 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankwells', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Members',
            new_name='Bankwells',
        ),
    ]
