# Generated by Django 3.2.12 on 2022-12-10 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankwells', '0002_rename_members_bankwells'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bankwells',
            new_name='Bankwell',
        ),
    ]
