# Generated by Django 3.2.12 on 2022-12-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankwells', '0003_rename_bankwells_bankwell'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankwell',
            name='anury_capicity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankwell',
            name='regestered_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
